<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegionsSeeder extends Seeder
{
    public function run(): void
    {
        // Départements
        DB::table('regions')->insert([
            ['nom_region'=>'Alibori','type_region'=>'departement','description'=>'Nord-est du Bénin'],
            ['nom_region'=>'Atacora','type_region'=>'departement','description'=>'Nord-ouest du Bénin'],
            ['nom_region'=>'Atlantique','type_region'=>'departement','description'=>'Sud-centre du Bénin'],
            ['nom_region'=>'Borgou','type_region'=>'departement','description'=>'Nord-centre du Bénin'],
            ['nom_region'=>'Collines','type_region'=>'departement','description'=>'Centre du Bénin'],
            ['nom_region'=>'Donga','type_region'=>'departement','description'=>'Nord-ouest du Bénin'],
            ['nom_region'=>'Kouffo','type_region'=>'departement','description'=>'Sud-ouest du Bénin'],
            ['nom_region'=>'Littoral','type_region'=>'departement','description'=>'Petit département comprenant Cotonou'],
            ['nom_region'=>'Mono','type_region'=>'departement','description'=>'Sud-ouest du Bénin'],
            ['nom_region'=>'Ouémé','type_region'=>'departement','description'=>'Sud-est du Bénin'],
            ['nom_region'=>'Plateau','type_region'=>'departement','description'=>'Centre-est du Bénin'],
            ['nom_region'=>'Zou','type_region'=>'departement','description'=>'Centre-sud du Bénin'],
        ]);

        // 77 communes + villes
        DB::table('regions')->insert([
            ['nom_region'=>'Banikoara','type_region'=>'commune'],
            ['nom_region'=>'Gogounou','type_region'=>'commune'],
            ['nom_region'=>'Kandi','type_region'=>'commune'],
            ['nom_region'=>'Karimama','type_region'=>'commune'],
            ['nom_region'=>'Malanville','type_region'=>'commune'],
            ['nom_region'=>'Segbana','type_region'=>'commune'],
            ['nom_region'=>'Boukoumbé','type_region'=>'commune'],
            ['nom_region'=>'Cobly','type_region'=>'commune'],
            ['nom_region'=>'Kérou','type_region'=>'commune'],
            ['nom_region'=>'Kouandé','type_region'=>'commune'],
            ['nom_region'=>'Matéri','type_region'=>'commune'],
            ['nom_region'=>'Natitingou','type_region'=>'commune'],
            ['nom_region'=>'Péhunco','type_region'=>'commune'],
            ['nom_region'=>'Tanguiéta','type_region'=>'commune'],
            ['nom_region'=>'Toucountouna','type_region'=>'commune'],
            ['nom_region'=>'Abomey-Calavi','type_region'=>'commune'],
            ['nom_region'=>'Allada','type_region'=>'commune'],
            ['nom_region'=>'Kpomassè','type_region'=>'commune'],
            ['nom_region'=>'Ouidah','type_region'=>'commune'],
            ['nom_region'=>'Sô-Ava','type_region'=>'commune'],
            ['nom_region'=>'Toffo','type_region'=>'commune'],
            ['nom_region'=>'Tori-Bossito','type_region'=>'commune'],
            ['nom_region'=>'Zè','type_region'=>'commune'],
            ['nom_region'=>'Bembèrèkè','type_region'=>'commune'],
            ['nom_region'=>'Kalalé','type_region'=>'commune'],
            ['nom_region'=>"N'Dali",'type_region'=>'commune'],
            ['nom_region'=>'Nikki','type_region'=>'commune'],
            ['nom_region'=>'Parakou','type_region'=>'commune'],
            ['nom_region'=>'Pèrèrè','type_region'=>'commune'],
            ['nom_region'=>'Sinendé','type_region'=>'commune'],
            ['nom_region'=>'Tchaourou','type_region'=>'commune'],
            ['nom_region'=>'Bantè','type_region'=>'commune'],
            ['nom_region'=>'Dassa-Zoumè','type_region'=>'commune'],
            ['nom_region'=>'Glazoué','type_region'=>'commune'],
            ['nom_region'=>'Ouèssè','type_region'=>'commune'],
            ['nom_region'=>'Savalou','type_region'=>'commune'],
            ['nom_region'=>'Savé','type_region'=>'commune'],
            ['nom_region'=>'Bassila','type_region'=>'commune'],
            ['nom_region'=>'Copargo','type_region'=>'commune'],
            ['nom_region'=>'Djougou','type_region'=>'commune'],
            ['nom_region'=>'Ouaké','type_region'=>'commune'],
            ['nom_region'=>'Aplahoué','type_region'=>'commune'],
            ['nom_region'=>'Djakotomey','type_region'=>'commune'],
            ['nom_region'=>'Klouékanmè','type_region'=>'commune'],
            ['nom_region'=>'Lalo','type_region'=>'commune'],
            ['nom_region'=>'Toviklin','type_region'=>'commune'],
            ['nom_region'=>'Dogbo-Tota','type_region'=>'commune'],
            ['nom_region'=>'Cotonou','type_region'=>'ville'],
            ['nom_region'=>'Athiémé','type_region'=>'commune'],
            ['nom_region'=>'Bopa','type_region'=>'commune'],
            ['nom_region'=>'Comé','type_region'=>'commune'],
            ['nom_region'=>'Grand-Popo','type_region'=>'commune'],
            ['nom_region'=>'Houéyogbé','type_region'=>'commune'],
            ['nom_region'=>'Lokossa','type_region'=>'commune'],
            ['nom_region'=>'Adjarra','type_region'=>'commune'],
            ['nom_region'=>'Adjohoun','type_region'=>'commune'],
            ['nom_region'=>'Aguégués','type_region'=>'commune'],
            ['nom_region'=>'Akpro-Missérété','type_region'=>'commune'],
            ['nom_region'=>'Avrankou','type_region'=>'commune'],
            ['nom_region'=>'Bonou','type_region'=>'commune'],
            ['nom_region'=>'Dangbo','type_region'=>'commune'],
            ['nom_region'=>'Porto Novo','type_region'=>'commune'],
            ['nom_region'=>'Sèmè-Kpodji','type_region'=>'commune'],
            ['nom_region'=>'Ifangni','type_region'=>'commune'],
            ['nom_region'=>'Adja-Ouèrè','type_region'=>'commune'],
            ['nom_region'=>'Kétou','type_region'=>'commune'],
            ['nom_region'=>'Pobè','type_region'=>'commune'],
            ['nom_region'=>'Sakété','type_region'=>'commune'],
            ['nom_region'=>'Abomey','type_region'=>'commune'],
            ['nom_region'=>'Agbangnizoun','type_region'=>'commune'],
            ['nom_region'=>'Bohicon','type_region'=>'commune'],
            ['nom_region'=>'Cové','type_region'=>'commune'],
            ['nom_region'=>'Djidja','type_region'=>'commune'],
            ['nom_region'=>'Ouinhi','type_region'=>'commune'],
            ['nom_region'=>'Za-Kpota','type_region'=>'commune'],
            ['nom_region'=>'Zangnanado','type_region'=>'commune'],
            ['nom_region'=>'Zogbodomey','type_region'=>'commune'],
        ]);
    }
}
